repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use the latest stable version
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0  # Use the latest stable version
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1  # Use the latest stable version
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-click