name = "calendar"
main = "cloudflare/src/index.js"
compatibility_date = "2026-03-27"
workers_dev = false

[[rules]]
type = "Text"
globs = ["**/*.yaml", "**/*.yml"]
fallthrough = true

[[routes]]
pattern = "calendar.corncob.app"
custom_domain = true

[vars]
YEAR_COUNT = "2"
