name = "calendar"
main = "cloudflare/src/index.js"
compatibility_date = "2026-03-27"
workers_dev = false

[build]
command = "npm run worker:build-static"

[[rules]]
type = "Text"
globs = ["**/*.yaml", "**/*.yml", "**/*.ics", "**/*.txt"]
fallthrough = true

[triggers]
crons = ["0 0 1 * *"]

[[routes]]
pattern = "calendar.corncob.app"
custom_domain = true

[[kv_namespaces]]
binding = "CALENDAR_CACHE"
id = "488a1e24b8e0473f8488079b5c65a553"
preview_id = "488a1e24b8e0473f8488079b5c65a553"

[vars]
YEAR_COUNT = "2"
