name = "us-holidays-calendar"
main = "cloudflare/src/index.js"
compatibility_date = "2026-03-27"
workers_dev = true

[vars]
HOLIDAYS_YAML_URL = "https://raw.githubusercontent.com/aaronshivers/calendar/master/src/generate_calendar/holidays.yaml"
YEAR_COUNT = "10"
