name: Update Calendar

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs on the 1st of every month at 00:00 UTC
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'

      - name: Format code with black
        run: devbox run format

      - name: Check formatting with black
        run: devbox run format-check

      - name: Run linting with flake8
        run: devbox run lint

      - name: Run type checking with mypy
        run: devbox run typecheck

      - name: Run tests with coverage
        run: devbox run test

      - name: Generate calendar
        run: devbox run generate

      - name: Verify calendar file exists
        run: |
          ls -la
          if [ -f "us_holidays.ics" ]; then
            echo "us_holidays.ics was generated successfully."
            cat us_holidays.ics
          else
            echo "Error: us_holidays.ics was not generated."
            exit 1
          fi

      - name: Create Pull Request
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update calendar for $(date +%Y-%m)"
          title: "Update calendar for $(date +%Y-%m)"
          body: "Automated update of us_holidays.ics for $(date +%Y-%m)."
          branch: update-calendar-$(date +%Y-%m)
          base: master
          delete-branch: true
          add-paths: us_holidays.ics
