name: Update Calendar

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs on the 1st of every month at 00:00 UTC

concurrency:
  group: calendar-update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check Poetry Version
        run: poetry --version

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: poetry install --verbose

      - name: Verify input files exist
        run: |
          ls -la
          if [ -f "src/holidays.json" ]; then
            echo "holidays.json exists"
            cat src/holidays.json
          else
            echo "Error: src/holidays.json not found"
            exit 1
          fi
          if [ -f "config/config.json" ]; then
            echo "config.json exists"
            cat config/config.json
          else
            echo "Error: config/config.json not found"
            exit 1
          fi

      - name: Generate calendar
        run: poetry run generate_calendar generate --verbose

      - name: Verify calendar file exists
        run: |
          ls -la
          if [ -f "us_holidays.ics" ]; then
            echo "us_holidays.ics was generated successfully."
            cat us_holidays.ics
          else
            echo "Error: us_holidays.ics was not generated."
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add -f us_holidays.ics
          git commit -m "Update calendar for $(date +%Y-%m)" || echo "No changes to commit"
          git push
