name: Update Holiday Calendar
on:
  schedule:
    - cron: '0 0 1 * *'  # Runs on the 1st of each month at midnight UTC
  push:
    branches:
      - master  # Runs on pushes to the master branch
  pull_request:
    branches:
      - master  # Runs on pull requests targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install Poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Generate iCal
      run: poetry run python generate_calendar.py
    - name: Commit and push changes
      if: github.event_name != 'pull_request'  # Only commit on schedule or push, not PR
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add us_holidays.ics
        git commit -m "Update calendar for $(date +%Y)" || echo "No changes to commit"
        git push